export const HANDS = [
  {
    id: "the_pair",
    name: "The Pair",
    pattern: ["NOUN", "NOUN"],
    baseMult: 1.5,
    description: "Two nouns. Simple connection.",
  },
  {
    id: "the_bark",
    name: "The Bark",
    pattern: ["NOUN", "VERB"],
    baseMult: 1.8,
    description: "A noun and its action. Quick and simple.",
  },
  {
    id: "the_action",
    name: "The Action",
    pattern: ["NOUN", "VERB", "NOUN"],
    baseMult: 3.0,
    description: "Subject acts on object.",
  },
  {
    id: "the_taste",
    name: "The Taste",
    pattern: ["NOUN", "VERB", "ADJ"],
    baseMult: 2.6,
    description: "A thing acts and lands on a quality.",
  },
  {
    id: "the_song",
    name: "The Song",
    pattern: ["NOUN", "VERB", "ADV"],
    baseMult: 2.7,
    description: "A thing acts in a particular way.",
  },
  {
    id: "the_description",
    name: "The Description",
    pattern: ["ADJ", "ADJ", "NOUN"],
    baseMult: 2.5,
    description: "Paint a picture.",
  },
  {
    id: "the_modifier",
    name: "The Modifier",
    pattern: ["ADV", "ADJ", "NOUN"],
    baseMult: 3.5,
    description: "An adverb intensifies a described thing.",
  },
  {
    id: "the_clause",
    name: "The Clause",
    pattern: ["ADJ", "NOUN", "VERB", "NOUN"],
    baseMult: 4.2,
    description: "A described thing acts on another thing.",
  },
  {
    id: "the_songline",
    name: "The Songline",
    pattern: ["NOUN", "VERB", "NOUN", "ADV"],
    baseMult: 4.6,
    description: "An action chain with a clean ending adverb.",
  },
  {
    id: "the_flood",
    name: "The Flood",
    pattern: ["NOUN", "ADV", "VERB", "NOUN"],
    baseMult: 4.8,
    description: "A noun leads into an adverb-driven action.",
  },
  {
    id: "the_scene",
    name: "The Scene",
    pattern: ["ADJ", "NOUN", "VERB", "ADV"],
    baseMult: 5.0,
    description: "A full scene in four words.",
  },
  {
    id: "the_contrast",
    name: "The Contrast",
    pattern: ["ADJ", "NOUN", "ADJ", "NOUN"],
    baseMult: 4.5,
    description: "Two described things.",
  },
  {
    id: "the_weather",
    name: "The Weather",
    pattern: ["ADJ", "NOUN", "VERB", "ADJ"],
    baseMult: 4.4,
    description: "A described subject lands on a final quality.",
  },
  {
    id: "the_service",
    name: "The Service",
    pattern: ["NOUN", "VERB", "ADJ", "NOUN"],
    baseMult: 4.7,
    description: "An action connects an object to a quality.",
  },
  {
    id: "the_epic",
    name: "The Epic",
    pattern: ["ADJ", "NOUN", "VERB", "ADJ", "NOUN"],
    baseMult: 6.2,
    description: "A full five-word sentence with a strong payoff.",
  },
];
